name = "Gruppe Adler Extras"
modname = "grad_extras"
prefix = "grad_extras"
author = "Gruppe Adler"
files = [
    "Adler_64.paa",
    "Adler_w_64.paa",
    "Adler_w_2.paa",
    "mod.cpp",
    "LICENSE",
    "README.md"
]
include = [
    "./include"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip {{modname}}_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
